---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant # provide a default test-kitchen driver, vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: '../../avvo_chef/data_bags'
  environments_path: '../../avvo_chef/environments'
  roles_path: '../../avvo_chef/roles'

  client_rb:
    environment: _default
  attributes:
    java:
      jdk_version: '8'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[curl]
    - recipe[java]
suites:
  - name: default
    run_list:
      - recipe[elasticsearch]
    attributes:
      elasticsearch:
        service:
          startup_method: init
          path_conf: "/srv/elasticsearch"
        install:
          version: 5.6.3
        configure: 
          instance_name: "elasticsearch"
          allocated_memory: "244m"
          path_conf: "/srv/elasticsearch"
          path_logs: "/var/log/elasticsearch"
          path_pid: "/var/run/elasticsearch"
          path_plugins: "/usr/share/elasticsearch/plugins"